# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f198563dbd5aea4dfd7d5c6108c715f69c06af1c693f03406fb90f1e42accbe418eb6daa7321dca3fff986453b35249720cbe7ca53a150cb46eaea98602cf853

test:
  secret_key_base: fea81860adbf9d5339393e7eb36d6401cf46d926e26200ff01fbb9b1ae36bb1f8caff897d014c346f767e05842006e33d5b45ac908c0dafa98a3e51147183de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
